include ../Makefile.inc

get_num.o: $(INC_PATH)*
	gcc -c $(INC_PATH)get_num.c

ugid_functions.o: $(INC_PATH)*
	gcc -c $(INC_PATH)ugid_functions.c

error_functions.o: $(INC_PATH)*
	gcc -c $(INC_PATH)error_functions.c