
simple_threads thread_incr producer_consumer: simple_threads.o thread_incr.o producer_consumer.o
	gcc -o simple_threads -pthread simple_threads.o
	gcc -o thread_incr -pthread thread_incr.o
	gcc -o producer_consumer -pthread producer_consumer.o

simple_threads.o:

thread_incr.o:

producer_consumer.o:
